version: "3.7"
services:
  # app:
  #   container_name: app
  #   build: .
  #   env_file: .env
  nextjs-ui:
    build:
        context: ./discord-landing
        args:
          - DISCORD_INVITE=${DISCORD_INVITE}
    ports:
        - "3000:3000"
    container_name: nextjs-ui
    stdin_open: true
    