version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env.local
  nextjs-ui:
    build:
        context: ./discord-landing
    ports:
        - "3000:3000"
    container_name: nextjs-ui
    stdin_open: true
    